export const API = 'API';
export const ON_REG_USER = 'ON_REG_USER';
export const ON_SERVICES = 'ON_SERVICES';
export const ON_SERVICES_BY_ID = 'ON_SERVICES_BY_ID';
export const ON_ADD_SERVICES = 'ON_ADD_SERVICES';
export const ON_REQUEST_SERVICE = 'ON_REQUEST_SERVICE';
export const ON_REQUESTED_SERVICES = 'ON_REQUESTED_SERVICES';
export const ON_PROVIDED_SERVICES = 'ON_PROVIDED_SERVICES';
export const ON_RECIVED_SERVICES = 'ON_RECIVED_SERVICES';
export const ON_API_SUCCESS = 'ON_API_SUCCESS';
export const ON_DEMO = 'ON_DEMO_USER';
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';

export const ON_GET_NEWS = 'ON_GET_NEWS';
export const ON_GET_TRANSACTIONS = 'ON_GET_TRANSACTIONS';

export const ON_GET_USER_BALANCE = 'ON_GET_USER_BALANCE';
